var GAME_LEVELS = [
  ["            yyyyyy                   yyyyyyyyyyyyyy                             ",
   "          yyyyyyyyyyyyy               yyyyyyyyyyyyyyy                           ",
   "       yyyyyyyyyyyyy                        yyyyyy                              ",
   "         yyyyyyyyyy                           yyy                               ",
   "            yyyyyyyy                                                            ",
   "                                                                                ",
   "                   b                                       b        xxx         ",
   "                  yy                              xx        xx      xx   xx!xx  ",
   "                yyyyyy                    o o   xxxxxx                  x!!!x   ",
   "            yyyyyyyyyyyyyy                                             xx!xx    ",
   "              yyyyyyyyy               xxxxx                             xxx     ",
   "                                                                            xx  ",
   "                               yyy      o o                                  x  ",
   "xxx                          yyyyyyy                                         x  ",
   "  x                                        xxxxx                             x  ",
   "  x          xxxx                o                                         o x  ",
   "  x  @       x  x   o o o                                             xxxxxxxx  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx   o  xxxxxxxxxxxxxxxxxx  ",
   "                              x   x                  x   x  x                    ",
   "                              x!!!x                  x!!!!!!x                    ",
   "                              x!!!x                  x!!!!!!x                    ",
   "                              xxxxx                  xxxxxxxx                    ",
   "                                                                                 ",
   "                                                                                 "],
  ["                                                                                    ",
   "                                                                                    ",
   "                                                                                    ",
   "                                                    o                               ",
   "                                                    y    xxxxxx   o   o   o    x    ",
   "                                                    y         x     o  g o  o  x    ",
   "                                                    y         xxxxxxxxxxxxxxxxxx    ",
   "                                                    y         xxxxxxxxxxxxxxxxxx    ",
   "                                                    y         xxx!!!!!!!!!!!xxxx    ",
   "                         yyyy                       y           xx!!!!!!!!!xxx      ",
   "                     yyyyyyyyyyyy                x  y  x           xxxxxxxx         ",
   "                     yyyy    yyyy                x  y  x                            ",
   "                                                 x  y  x                            ",
   "                                                 x  y  x                            ",
   "                                                 x  y  x                            ",
   "x                                                x  y  x        xx     xx           ",
   "x                                                                                   ",
   "x                           x   x          x                                        ",
   "x                           x o x          x    xx            o           o         ",
   "x     @       x             x   x    x          x     x       x           x         ",
   "x    xxx      x             x   x    x          x     xxxxxx     xxxxxx      xxxx    x",
   "x    x x             yy   xxxxxxxx o x        xxx     x         p       p       x    x",
   "x    x x           yy     x!!!!!!x   xxx!!!!!!!!xxxxxxx!!!!!!!!!!x!!!!!!!!!!!!!!x    x",
   "x    x x          yy      x!!!!!!x                !!!!!!!!!!x!x!!xxx!!xxx!xxxxxxx    x",
   "x     o         yy                                             !! o !! o !!          x",
   "x         xxx p                             p    p                                   x",
   "!!!xxxxxxx!!!!!!!       xxxxxxxxxxx       xxxxxxxxxxxxxx                             x",
   "!!!!x x!!!!!!x !!!!!!!!!!x!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!x x!!!!!!x !!!!!!!!!!x!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!!!                        "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                   xxxxxxxx                                                                                   ",
   "              xxxx g       xxxx                                                                               ",
   "         xxxxx                 xxxxx                                                                          ",
   "                      o                                              yy                                       ",
   "                    x   x                                           yyyyy           o                         ",
   "                xxxx     xxxx                                                 !!!  xxx                        ",
   "             xxx     yyy     xxxx                                             !x!                             ",
   "         xxxx         y          xxxxxx   xx                x g        x                                      ",
   "                      y               x   x                 x   oooo   x       xxx                            ",
   "                     yyy              x   x                 x         gx      x!!!x                           ",
   "                                      x   x                 xxxxxxxxxxxx       xxx                            ",
   "                                     xx   xx      x   x      x                                                ",
   "                    o yyy             x   xxxxxxxxx   xxxxxxxx              xxx                               ",
   "                 yyyyyy               x   x           x                    x!!!x                              ",
   "                    yyy      g      o x   x           x                 yy  xxx                             ",
   "                            xxxxxxxxxxx   xx p        x                yyyy                                   ",
   "       yyyy                           x   x xxxx     gx            xxx    y                                   ",
   "                                      x   x           x           x!!!x    y                                  ",
   "                 yy                   x   x       xxxxx     o      xxx      yxxx                              ",
   "             yyyyyyyyy               xx   xx       p  x   yyyyy             x!!!x                             ",
   "                                      x   x           x                      xxx        xxx                   ",
   "         yy                           x   x g         x             xx                 x!!!x                  ",
   "         yyyy   p  o             x!!!!!!!!!!!!xxx         xx        xx                  xxx                   ",
   "                yyyy             x!!!!!!!!!!!!!!x         xx                                                  ",
   "                             xxxxxxxxxxxxxxxxxxxxxxxxx                                                        ",
   "                             xx           xx                                         xxxxx                    ",
   "  xxx              yyyy       x            xx                                         x!!!x               xxx ",
   "  x x      o                  x                                                    xxx                    x x ",
   "  x      yyyy                 x     xxxxx      xxxxxxx                        xxxxx                         x  ",
   "  x                           x                                           x   x                             x  ",
   "  x          yyy              x                                          x x x                              x  ",
   "  x                           x           x        xxxx     xxxx     xxx   xxx       xxx                    x  ",
   "  x                xxx        x    o o    x          p        p          x        xxxxx                     x  ",
   "  x               xxxxx       x           x                             xxx        xxx            o         x  ",
   "  x               oxxxo       x    xxx    x g                           x x                      xxx        x  ",
   "  x                xxx        xxxxxxxxxxxxx  x oo x    x oo x    x oo  xx xx        p            xxx        x  ",
   "  x      @          x         x           x!!x    x!!!!x    x!!!!x    xx   xx                     g         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "                                                                                                  x xxx       ",
   "                          o                                                                       x x x       ",
   "                                                                                             o o oxxx x       ",
   "                   xxx                                                                                x       ",
   "       !  o  !                                                xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxx       ",
   "       x     x                                                x   x x   x x   x x   x x   x x   x x           ",
   "       x= o  x            x                                   xxx x xxx x xxx x xxx x xxx x xxx x xxxxx       ",
   "       x     x                                                  x x   x x   x x   x x   x x   x x     x       ",
   "       !  o  !            o                                  xxxx xxxxx xxxxx xxxxx xxxxx xxxxx xxxxxxx       ",
   "                                                                                                              ",
   "          o              xxx                              xx                                                  ",
   "                          p                                                                                    ",
   "                                                                                      y       y   yyyyy   y   y        ",
   "                                                      xx                               y     y    y   y   y   y     ",
   "                   xxx         xxx                                                      y   y     y   y   y   y     ",
   "                    g           g                                                        y y      y   y   y   y    ",
   "                          o                                                               y       y   y   y   y    ",
   "                                                          xx     xx                       y       y   y   y   y    ",
   "             xxx         xxx         xxx                                                  y       yyyyy   yyyyy          ",
   "              p           p          p                                                                       ",
   "                                                                 ||                y           y   y   y     y     ",
   "  xxxxxxxxxxx                                                                       y         y        yy    y     ",
   "  x         x o xxxxxxxxx o xxxxxxxxx o xx                                           y   y   y     y   y y   y       ",
   "  x         x   x       x   x       x   x                 ||                          y y y y      y   y  y  y        ",
   "  x  @      xxxxx   o   xxxxx   o   xxxxx                                              y   y       y   y   y y      ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                        y   y    yy    ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
